apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw2-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cw2-server
  template:
    metadata:
      labels:
        app: cw2-server
    spec:
      containers:
      - name: cw2-server
        image: cw2-server:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cw2-server-service
spec:
  selector:
    app: cw2-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  ---
  - name: Deploy cw2-server to Kubernetes
    hosts: localhost
    tasks:
      - name: Apply Kubernetes deployment
        kubernetes.core.k8s:
          state: present
          definition: "{{ lookup('file', 'deployment.yaml') }}"
      - name: Apply Kubernetes service
        kubernetes.core.k8s:
          state: present
          definition: "{{ lookup('file', 'service.yaml') }}"