---
- name: Scale deployment for rolling updates
  hosts: localhost
  tasks:
    - name: Scale deployment
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: my-deployment
            namespace: default
          spec:
            replicas: 3  # Adjust the number of replicas as needed
            selector:
              matchLabels:
                app: my-app
            template:
              metadata:
                labels:
                  app: my-app
              spec:
                containers:
                - name: my-container
                  image: my-image:latest
                  ports:
                  - containerPort: 80